export enum Stack {
    REACT = "React",
    TYPESCRIPT = "TypeScript",
    JAVASCRIPT = "JavaScript",
    NATIVE = "React Native",
    PHP = "PHP",
    LARAVEL = "Laravel",
    FIGMA = "Figma",
    UNITY = "Unity",
    PYTHON = "Python",
    TENSORFLOW = "TensorFlow",
    PYTORCH = "PyTorch",
    KOTLIN = "Kotlin",
    KERAS = "Keras",
    MOTOKO = "Motoko",
    GODOT = "Godot",
    SUPABASE = "Supabase",
    NEXTJS = "Next.js",
    POSTGRESQL = "PostgreSQL",
    JEST = "Jest",
    JAVA = "Java",
    GO = "Go",
    MONGODB = "MongoDB",
    SQL = "SQL",
}
